#!/usr/bin/env python
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from commandant import TestCommand
from plano import *

import tests

path = "/alpha/beta.ext"
path_split = "/alpha", "beta.ext"
path_split_extension = "/alpha/beta", ".ext"

result = join(*path_split)
assert result == path, result

result = split(path)
assert result == path_split, result

result = split_extension(path)
assert result == path_split_extension, result

##

print(unique_id())
print(unique_id(4))

##

temp_dir = make_temp_dir()

alpha_dir = make_dir(join(temp_dir, "alpha-dir"))
alpha_file = touch(join(alpha_dir, "alpha-file"))

beta_dir = make_dir(join(temp_dir, "beta-dir"))
beta_file = touch(join(beta_dir, "beta-file"))

copied_file = copy(alpha_file, beta_dir)
assert copied_file == join(beta_dir, "alpha-file")

copied_dir = copy(alpha_dir, beta_dir)
assert copied_dir == join(beta_dir, "alpha-dir")

moved_file = move(beta_file, alpha_dir)
assert moved_file == join(alpha_dir, "beta-file")

moved_dir = move(beta_dir, alpha_dir)
assert moved_dir == join(alpha_dir, "beta-dir")

if __name__ == "__main__":
    command = TestCommand([tests])
    command.main()
